# Exclude ActiveMQ/JMS Auto-configurations in local development profile
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration,org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
